### ISSUE TITLE
Missing ndarray explanation diagram

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/BootCamp#16]
```
Image(filename='ndarray_layout.png')
```

> IOError: [Errno 2] No such file or directory: u'ndarray_layout.png'

@j-dr Can you either check in this file, or replace the `Image`  call with a `<img>` call, please? Thanks!

**Comment by j-dr** [comment]
Done!

**Comment by drphilmarshall** [comment]
Thanks!
