### ISSUE TITLE
Add information about basic setup for windows computers to documentation

### ISSUE THREAD

**Issue by eacharles** [KIPAC/BootCamp#29]
This should probably include, at a minimum, how to use some terminal emulator and how to run juypter notebooks.

**Comment by sidneymau** [comment]
This is done with commits ce10a2995d1041163d403220f209cae67c2aa374–2eca8749b61f77188db9748625457d1cf846ab6a and https://github.com/KIPAC/BootCamp/blob/master/docs/windows_setup.md. Other information available at https://sidneymau.com/setup.html.
