### ISSUE TITLE
Add information about stanford computer accounts to documentation

### ISSUE THREAD

**Issue by eacharles** [KIPAC/BootCamp#30]
Either update the information here: https://github.com/KIPAC/BootCamp/blob/master/docs/stanford_computing.md

Or change the link in this file to point at useful information:
https://github.com/KIPAC/BootCamp/blob/master/docs/Getting_Started.md

**Comment by abmantz** [comment]
That first linked page. Wow.

I have no useful knowledge about Sherlock. We do have a blurb about Stanford's non-Sherlock unix computing in the [phys 366 pages](https://github.com/KIPAC/StatisticalMethods/blob/master/doc/Stanford.md#computing), which I could update/copy. I think all summer students should have access to this.

**Comment by jessmuir** [comment]
Added some links and info about Sherlock. I've only used it for batch jobs so don't have much useful info about using it interactively.
